name: SimpleMetaPipeline-env

channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - r-base=4.2
  - r-tidyverse=2.0
  - vsearch=2.14
  - swarm=3.1 
  - cutadapt=4.5 
  - blast=2.5
  - bioconductor-dada2=1.26
  - r-seqinr=4.2-16
  - bioconductor-decipher=2.26
  - r-gridextra=2.3
  - bioconductor-shortread=1.56 
  - bioconductor-biostrings=2.66
  - r-seqinr=4.2
  - r-devtools=2.4


#Some R pacakge are not installed with conda as they are not hosted on any channel.
# These are installed (by R, in the normal way) in the version of R within 
# SimpleMetaPipeline-env the first time you run the pipeline. 
# These are:
  #Lulu